/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/hpe-storage/k8s-custom-resources/pkg/apis/hpestorage/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// HPENodeInfoLister helps list HPENodeInfos.
type HPENodeInfoLister interface {
	// List lists all HPENodeInfos in the indexer.
	List(selector labels.Selector) (ret []*v1.HPENodeInfo, err error)
	// Get retrieves the HPENodeInfo from the index for a given name.
	Get(name string) (*v1.HPENodeInfo, error)
	HPENodeInfoListerExpansion
}

// hPENodeInfoLister implements the HPENodeInfoLister interface.
type hPENodeInfoLister struct {
	indexer cache.Indexer
}

// NewHPENodeInfoLister returns a new HPENodeInfoLister.
func NewHPENodeInfoLister(indexer cache.Indexer) HPENodeInfoLister {
	return &hPENodeInfoLister{indexer: indexer}
}

// List lists all HPENodeInfos in the indexer.
func (s *hPENodeInfoLister) List(selector labels.Selector) (ret []*v1.HPENodeInfo, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.HPENodeInfo))
	})
	return ret, err
}

// Get retrieves the HPENodeInfo from the index for a given name.
func (s *hPENodeInfoLister) Get(name string) (*v1.HPENodeInfo, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("hpenodeinfo"), name)
	}
	return obj.(*v1.HPENodeInfo), nil
}
