/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	hpestoragev1 "github.com/hpe-storage/k8s-custom-resources/pkg/apis/hpestorage/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeHPENodeInfos implements HPENodeInfoInterface
type FakeHPENodeInfos struct {
	Fake *FakeStorageV1
}

var hpenodeinfosResource = schema.GroupVersionResource{Group: "storage.hpe.com", Version: "v1", Resource: "hpenodeinfos"}

var hpenodeinfosKind = schema.GroupVersionKind{Group: "storage.hpe.com", Version: "v1", Kind: "HPENodeInfo"}

// Get takes name of the hPENodeInfo, and returns the corresponding hPENodeInfo object, and an error if there is any.
func (c *FakeHPENodeInfos) Get(name string, options v1.GetOptions) (result *hpestoragev1.HPENodeInfo, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(hpenodeinfosResource, name), &hpestoragev1.HPENodeInfo{})
	if obj == nil {
		return nil, err
	}
	return obj.(*hpestoragev1.HPENodeInfo), err
}

// List takes label and field selectors, and returns the list of HPENodeInfos that match those selectors.
func (c *FakeHPENodeInfos) List(opts v1.ListOptions) (result *hpestoragev1.HPENodeInfoList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(hpenodeinfosResource, hpenodeinfosKind, opts), &hpestoragev1.HPENodeInfoList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &hpestoragev1.HPENodeInfoList{ListMeta: obj.(*hpestoragev1.HPENodeInfoList).ListMeta}
	for _, item := range obj.(*hpestoragev1.HPENodeInfoList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested hPENodeInfos.
func (c *FakeHPENodeInfos) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(hpenodeinfosResource, opts))
}

// nolint: dupl
// Create takes the representation of a hPENodeInfo and creates it.  Returns the server's representation of the hPENodeInfo, and an error, if there is any.
func (c *FakeHPENodeInfos) Create(hPENodeInfo *hpestoragev1.HPENodeInfo) (result *hpestoragev1.HPENodeInfo, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(hpenodeinfosResource, hPENodeInfo), &hpestoragev1.HPENodeInfo{})
	if obj == nil {
		return nil, err
	}
	return obj.(*hpestoragev1.HPENodeInfo), err
}

// nolint: dupl
// Update takes the representation of a hPENodeInfo and updates it. Returns the server's representation of the hPENodeInfo, and an error, if there is any.
func (c *FakeHPENodeInfos) Update(hPENodeInfo *hpestoragev1.HPENodeInfo) (result *hpestoragev1.HPENodeInfo, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(hpenodeinfosResource, hPENodeInfo), &hpestoragev1.HPENodeInfo{})
	if obj == nil {
		return nil, err
	}
	return obj.(*hpestoragev1.HPENodeInfo), err
}

// Delete takes name of the hPENodeInfo and deletes it. Returns an error if one occurs.
func (c *FakeHPENodeInfos) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(hpenodeinfosResource, name), &hpestoragev1.HPENodeInfo{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeHPENodeInfos) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(hpenodeinfosResource, listOptions)

	_, err := c.Fake.Invokes(action, &hpestoragev1.HPENodeInfoList{})
	return err
}

// Patch applies the patch and returns the patched hPENodeInfo.
func (c *FakeHPENodeInfos) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *hpestoragev1.HPENodeInfo, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(hpenodeinfosResource, name, pt, data, subresources...), &hpestoragev1.HPENodeInfo{})
	if obj == nil {
		return nil, err
	}
	return obj.(*hpestoragev1.HPENodeInfo), err
}
